# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm2(object):
    def setupUi(self, MainForm2):
        MainForm2.setObjectName("MainForm2")
        MainForm2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainForm2)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 90, 471, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.MiangridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.MiangridLayout.setContentsMargins(0, 0, 0, 0)
        self.MiangridLayout.setObjectName("MiangridLayout")
        MainForm2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainForm2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        MainForm2.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainForm2)
        self.toolBar.setObjectName("toolBar")
        MainForm2.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fileActionOpen = QtWidgets.QAction(MainForm2)
        self.fileActionOpen.setObjectName("fileActionOpen")
        self.actionnew = QtWidgets.QAction(MainForm2)
        self.actionnew.setObjectName("actionnew")
        self.actionclos = QtWidgets.QAction(MainForm2)
        self.actionclos.setObjectName("actionclos")
        self.addWinAction = QtWidgets.QAction(MainForm2)
        self.addWinAction.setObjectName("addWinAction")
        self.menu_F.addAction(self.fileActionOpen)
        self.menu_F.addAction(self.actionnew)
        self.menu_F.addAction(self.actionclos)
        self.menubar.addAction(self.menu_F.menuAction())
        self.toolBar.addAction(self.addWinAction)

        self.retranslateUi(MainForm2)
        QtCore.QMetaObject.connectSlotsByName(MainForm2)

    def retranslateUi(self, MainForm2):
        _translate = QtCore.QCoreApplication.translate
        MainForm2.setWindowTitle(_translate("MainForm2", "MainWindow"))
        self.menu_F.setTitle(_translate("MainForm2", "文件(&F)"))
        self.toolBar.setWindowTitle(_translate("MainForm2", "toolBar"))
        self.fileActionOpen.setText(_translate("MainForm2", "open"))
        self.actionnew.setText(_translate("MainForm2", "new "))
        self.actionclos.setText(_translate("MainForm2", "close"))
        self.addWinAction.setText(_translate("MainForm2", "添加窗体"))
        self.addWinAction.setToolTip(_translate("MainForm2", "添加窗体"))
