# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.py'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from login import Ui_MainWindow as A_Ui  # a界面的库
# from MainWindow import Ui_MainWindow as B_Ui  # b界面的库
from MainWindow import Ui_MainWindow as B_Ui
from PyQt5 import QtCore, QtWidgets
import sys
class AUi(QtWidgets.QMainWindow, A_Ui):
    def __init__(self):
        super(AUi, self).__init__()
        self.setupUi(self)
        self.pushButton.clicked.connect(self.login)

    def login(self):
        user = self.user_lineedit.text()
        pwd = self.pwd_lineedit.text()
        if user == '123' and pwd == '123':
            self.b_window = BUi()
            self.b_window.show()
            self.close()


class BUi(QtWidgets.QMainWindow, B_Ui):
    def __init__(self):
        super(BUi, self).__init__()
        self.setupUi(self)
        self.btn_1.clicked.connect(self.display_stack)
        self.btn_2.clicked.connect(self.display_stack)
        self.btn_3.clicked.connect(self.display_stack)
        self.btn_4.clicked.connect(self.display_stack)
        self.btn_5.clicked.connect(self.display_stack)
        self.btn_6.clicked.connect(self.display_stack)
        self.btn_7.clicked.connect(self.display_stack)
        self.btn_8.clicked.connect(self.display_stack)

    def display_stack(self):
        sender = self.sender()
        index = eval(sender.objectName().split('_')[-1]) - 1
        self.stackedWidget.setCurrentIndex(index)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    a = AUi()
    a.show()
    # b = BUi()
    # # button是你定义的按钮
    # a.pushButton.clicked.connect(
    #     lambda: {a.close(), b.show()}
    # )
    sys.exit(app.exec_())

