# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'email_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_emailWindow(object):
    def setupUi(self, emailWindow):
        emailWindow.setObjectName("emailWindow")
        emailWindow.resize(446, 483)
        self.centralwidget = QtWidgets.QWidget(emailWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_recevier = QtWidgets.QLineEdit(self.centralwidget)
        self.text_recevier.setGeometry(QtCore.QRect(30, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_recevier.setFont(font)
        self.text_recevier.setObjectName("text_recevier")
        self.text_title = QtWidgets.QLineEdit(self.centralwidget)
        self.text_title.setGeometry(QtCore.QRect(30, 60, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.text_title.setFont(font)
        self.text_title.setObjectName("text_title")
        self.text_content = QtWidgets.QTextEdit(self.centralwidget)
        self.text_content.setGeometry(QtCore.QRect(30, 100, 381, 261))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.text_content.setFont(font)
        self.text_content.setDocumentTitle("")
        self.text_content.setObjectName("text_content")
        self.button_send = QtWidgets.QPushButton(self.centralwidget)
        self.button_send.setGeometry(QtCore.QRect(30, 427, 381, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_send.setFont(font)
        self.button_send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_send.setObjectName("button_send")
        self.button_addFile = QtWidgets.QPushButton(self.centralwidget)
        self.button_addFile.setGeometry(QtCore.QRect(30, 390, 381, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.button_addFile.setFont(font)
        self.button_addFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_addFile.setObjectName("button_addFile")
        self.label_fileName = QtWidgets.QLabel(self.centralwidget)
        self.label_fileName.setGeometry(QtCore.QRect(60, 369, 351, 16))
        self.label_fileName.setObjectName("label_fileName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 366, 31, 21))
        self.label.setStyleSheet("image: url(:/icons/link.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        emailWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(emailWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 446, 26))
        self.menubar.setObjectName("menubar")
        emailWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(emailWindow)
        self.statusbar.setObjectName("statusbar")
        emailWindow.setStatusBar(self.statusbar)

        self.retranslateUi(emailWindow)
        QtCore.QMetaObject.connectSlotsByName(emailWindow)

    def retranslateUi(self, emailWindow):
        _translate = QtCore.QCoreApplication.translate
        emailWindow.setWindowTitle(_translate("emailWindow", "发邮件"))
        self.text_recevier.setPlaceholderText(_translate("emailWindow", "收件邮箱"))
        self.text_title.setPlaceholderText(_translate("emailWindow", "主题"))
        self.text_content.setPlaceholderText(_translate("emailWindow", "正文"))
        self.button_send.setText(_translate("emailWindow", "发送邮件"))
        self.button_addFile.setText(_translate("emailWindow", "添加附件"))
        self.label_fileName.setText(_translate("emailWindow", "未选择附件"))
import res_rc
