# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 711)
        MainWindow.setStyleSheet("#tab_2 QPushButton{\n"
"    margin: 5px;\n"
"    border-radius: 10px;\n"
"    height:60;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"#tab_2 QPushButton:hover{\n"
"    \n"
"    background-color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 20, 801, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("::tab{\n"
"    width: 198;\n"
"    height:50;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-right: 1px solid  rgb(200, 200, 200);\n"
"}\n"
"::tab:last {\n"
"    border:none;\n"
"}\n"
"::tab:hover {\n"
"    \n"
"    background-color: rgb(173, 173, 173);\n"
"}\n"
"::tab:selected {\n"
"    background-color: rgb(173, 173, 173);\n"
"}\n"
"::pane{\n"
"    background-color: transparent;\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_question = QtWidgets.QLabel(self.tab_2)
        self.label_question.setGeometry(QtCore.QRect(30, 20, 731, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_question.sizePolicy().hasHeightForWidth())
        self.label_question.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_question.setFont(font)
        self.label_question.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_question.setStyleSheet("background-color: rgba(172, 197, 224,100);\n"
"border-radius:0;")
        self.label_question.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_question.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_question.setLineWidth(0)
        self.label_question.setMidLineWidth(0)
        self.label_question.setTextFormat(QtCore.Qt.AutoText)
        self.label_question.setScaledContents(False)
        self.label_question.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_question.setWordWrap(True)
        self.label_question.setIndent(-1)
        self.label_question.setOpenExternalLinks(False)
        self.label_question.setObjectName("label_question")
        self.button_next = QtWidgets.QPushButton(self.tab_2)
        self.button_next.setGeometry(QtCore.QRect(660, 555, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_next.setFont(font)
        self.button_next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_next.setObjectName("button_next")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 230, 711, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.answer_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_1.setFont(font)
        self.answer_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.answer_1.setObjectName("answer_1")
        self.verticalLayout.addWidget(self.answer_1)
        self.answer_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_2.setFont(font)
        self.answer_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.answer_2.setObjectName("answer_2")
        self.verticalLayout.addWidget(self.answer_2)
        self.answer_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_3.setFont(font)
        self.answer_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.answer_3.setObjectName("answer_3")
        self.verticalLayout.addWidget(self.answer_3)
        self.answer_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_4.setFont(font)
        self.answer_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.answer_4.setObjectName("answer_4")
        self.verticalLayout.addWidget(self.answer_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_3)
        self.treeWidget.setGeometry(QtCore.QRect(20, 20, 741, 561))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeWidget.setFont(font)
        self.treeWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.treeWidget.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"width:500;\n"
"font-size: 30;\n"
"\n"
"")
        self.treeWidget.setLineWidth(1)
        self.treeWidget.setMidLineWidth(0)
        self.treeWidget.setAutoScrollMargin(16)
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setIndentation(0)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setColumnCount(2)
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.treeWidget.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.treeWidget.headerItem().setFont(1, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(315)
        self.treeWidget.header().setMinimumSectionSize(37)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("")
        self.tab_4.setObjectName("tab_4")
        self.label_id = QtWidgets.QLabel(self.tab_4)
        self.label_id.setGeometry(QtCore.QRect(280, 140, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_id.setFont(font)
        self.label_id.setScaledContents(False)
        self.label_id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id.setObjectName("label_id")
        self.label_time = QtWidgets.QLabel(self.tab_4)
        self.label_time.setGeometry(QtCore.QRect(50, 250, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.button_view = QtWidgets.QPushButton(self.tab_4)
        self.button_view.setGeometry(QtCore.QRect(40, 510, 251, 41))
        self.button_view.setObjectName("button_view")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(340, 30, 111, 111))
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setStyleSheet("image: url(:/icons/user.png);")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 761, 371))
        self.label_2.setStyleSheet("background-color: rgba(172, 197, 224,100);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label_id.raise_()
        self.label_time.raise_()
        self.button_view.raise_()
        self.label.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "首页"))
        self.label_question.setText(_translate("MainWindow", "TextLabel"))
        self.button_next.setText(_translate("MainWindow", "下一题"))
        self.answer_1.setText(_translate("MainWindow", "PushButton"))
        self.answer_2.setText(_translate("MainWindow", "PushButton"))
        self.answer_3.setText(_translate("MainWindow", "PushButton"))
        self.answer_4.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "实验安全"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "实验名称"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "学习时长"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "实验一  雷诺实验"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "实验二  机械能转化实验"))
        self.treeWidget.topLevelItem(1).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "实验三  流体阻力的测定"))
        self.treeWidget.topLevelItem(2).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "实验四  离心泵性能的测定"))
        self.treeWidget.topLevelItem(3).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "实验五  恒压过滤实验"))
        self.treeWidget.topLevelItem(4).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "实验六  综合传热实验"))
        self.treeWidget.topLevelItem(5).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "实验七  精馏实验"))
        self.treeWidget.topLevelItem(6).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindow", "实验八  CO2吸收-解吸实验"))
        self.treeWidget.topLevelItem(7).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.topLevelItem(8).setText(0, _translate("MainWindow", "实验九  洞道干燥实验"))
        self.treeWidget.topLevelItem(8).setText(1, _translate("MainWindow", "-"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "实验选择"))
        self.label_id.setText(_translate("MainWindow", "显示用户账号"))
        self.label_time.setText(_translate("MainWindow", "学习总时长："))
        self.button_view.setText(_translate("MainWindow", "查看“实验安全”测验结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "我的"))
import res_rc
